import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme/ThemeProvider";
import {ConvexClientProvider} from "@/provider/ConvexProvider";
import { TooltipProvider } from "@/components/ui/tooltip";
import {Toaster} from "react-hot-toast"
export const metadata: Metadata = {
  title: "Whatsapp Clone",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        > 
        <TooltipProvider>
          <ConvexClientProvider>
          {children}
          <Toaster />
          </ConvexClientProvider>
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
